### ISSUE TITLE
Build failure - unable to delete file

### ISSUE THREAD

**Issue by finoradin** [LibraryOfCongress/bagit-java#25]
mvn package is failing for me on Windows 7, with the following error

```
-------------------------------------------------------------------------------
Test set: gov.loc.repository.bagit.writer.impl.ZipBagWriterTest
-------------------------------------------------------------------------------
Tests run: 4, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.062 sec <<< FAILURE! - in gov.loc.repository.bagit.writer.impl.ZipBagWriterTest
testOverwrite(gov.loc.repository.bagit.writer.impl.ZipBagWriterTest)  Time elapsed: 0.031 sec  <<< ERROR!
java.lang.RuntimeException: Error deleting C:\Users\MoMA\Documents\GitHub\bagit-java\target\unit-test-data\bags\foo.zip: Unable to delete file: C:\Users\MoMA\Documents\GitHub\bagit-java\target\unit-test-data\bags\foo.zip
	at gov.loc.repository.bagit.utilities.TempFileHelper.switchTemp(TempFileHelper.java:34)
	at gov.loc.repository.bagit.writer.impl.AbstractWriter.switchTemp(AbstractWriter.java:47)
	at gov.loc.repository.bagit.writer.impl.ZipWriter.endBag(ZipWriter.java:91)
	at gov.loc.repository.bagit.impl.AbstractBag.accept(AbstractBag.java:475)
	at gov.loc.repository.bagit.writer.impl.ZipWriter.write(ZipWriter.java:158)
	at gov.loc.repository.bagit.writer.impl.AbstractWriterTest.testOverwrite(AbstractWriterTest.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.io.IOException: Unable to delete file: C:\Users\MoMA\Documents\GitHub\bagit-java\target\unit-test-data\bags\foo.zip
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2279)
	at gov.loc.repository.bagit.utilities.TempFileHelper.switchTemp(TempFileHelper.java:30)
	at gov.loc.repository.bagit.writer.impl.AbstractWriter.switchTemp(AbstractWriter.java:47)
	at gov.loc.repository.bagit.writer.impl.ZipWriter.endBag(ZipWriter.java:91)
	at gov.loc.repository.bagit.impl.AbstractBag.accept(AbstractBag.java:475)
	at gov.loc.repository.bagit.writer.impl.ZipWriter.write(ZipWriter.java:158)
	at gov.loc.repository.bagit.writer.impl.AbstractWriterTest.testOverwrite(AbstractWriterTest.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

testWriter(gov.loc.repository.bagit.writer.impl.ZipBagWriterTest)  Time elapsed: 0.015 sec  <<< ERROR!
java.lang.RuntimeException: Error deleting C:\Users\MoMA\Documents\GitHub\bagit-java\target\unit-test-data\bags\foo.zip: Unable to delete file: C:\Users\MoMA\Documents\GitHub\bagit-java\target\unit-test-data\bags\foo.zip
	at gov.loc.repository.bagit.utilities.TempFileHelper.switchTemp(TempFileHelper.java:34)
	at gov.loc.repository.bagit.writer.impl.AbstractWriter.switchTemp(AbstractWriter.java:47)
	at gov.loc.repository.bagit.writer.impl.ZipWriter.endBag(ZipWriter.java:91)
	at gov.loc.repository.bagit.impl.AbstractBag.accept(AbstractBag.java:475)
	at gov.loc.repository.bagit.writer.impl.ZipWriter.write(ZipWriter.java:158)
	at gov.loc.repository.bagit.writer.impl.AbstractWriterTest.testWriter(AbstractWriterTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.io.IOException: Unable to delete file: C:\Users\MoMA\Documents\GitHub\bagit-java\target\unit-test-data\bags\foo.zip
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2279)
	at gov.loc.repository.bagit.utilities.TempFileHelper.switchTemp(TempFileHelper.java:30)
	at gov.loc.repository.bagit.writer.impl.AbstractWriter.switchTemp(AbstractWriter.java:47)
	at gov.loc.repository.bagit.writer.impl.ZipWriter.endBag(ZipWriter.java:91)
	at gov.loc.repository.bagit.impl.AbstractBag.accept(AbstractBag.java:475)
	at gov.loc.repository.bagit.writer.impl.ZipWriter.write(ZipWriter.java:158)
	at gov.loc.repository.bagit.writer.impl.AbstractWriterTest.testWriter(AbstractWriterTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

**Comment by johnscancella** [comment]
This is not a bug. Windows is locking that file for some reason (perhaps you have the file explorer open to it?)
Check out http://www.howtogeek.com/128680/how-to-delete-move-or-rename-locked-files-in-windows/ for more info on how windows does file locking.
