### ISSUE TITLE
Issues running on larger files on Network-Attached Storage devices?

### ISSUE THREAD

**Issue by hoeyjeinen** [LibraryOfCongress/bagit-java#33]
Hi, I'm wondering if there have been other reported issues with BagIt not running successfully on files that are stored on Network-Attached Storage and processed locally. The tool will work on some files but not others, and from my observation it seems to only work on smaller files (video files smaller than 1 GB are fine but anything larger fails to run). 

Here is the full log report:

2016-02-11 12:50:13,377 [main] INFO  CommandLineBagDriver : Performing operation: baginplace
2016-02-11 12:50:13,390 [main] INFO  PreBagImpl : Making a bag in place at /Users/joeyheinen/Library/home-1/University Photograph Media/UPM_0463/Preservation Master
2016-02-11 12:50:13,423 [main] ERROR CommandLineBagDriver : Error: java.io.FileNotFoundException: Source '/Users/joeyheinen/Library/home-1/University Photograph Media/UPM_0463/Preservation Master/._.DS_Store' does not exist
java.lang.RuntimeException: java.io.FileNotFoundException: Source '/Users/joeyheinen/Library/home-1/University Photograph Media/UPM_0463/Preservation Master/._.DS_Store' does not exist
	at gov.loc.repository.bagit.impl.PreBagImpl.makeBagInPlace(PreBagImpl.java:100)
	at gov.loc.repository.bagit.driver.CommandLineBagDriver.performOperation(CommandLineBagDriver.java:852)
	at gov.loc.repository.bagit.driver.CommandLineBagDriver.execute(CommandLineBagDriver.java:411)
	at gov.loc.repository.bagit.driver.CommandLineBagDriver.main(CommandLineBagDriver.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.classworlds.Launcher.launchStandard(Launcher.java:353)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:264)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: java.io.FileNotFoundException: Source '/Users/joeyheinen/Library/home-1/University Photograph Media/UPM_0463/Preservation Master/._.DS_Store' does not exist
	at org.apache.commons.io.FileUtils.moveToDirectory(FileUtils.java:2169)
	at gov.loc.repository.bagit.impl.PreBagImpl.makeBagInPlace(PreBagImpl.java:81)
	... 11 more
2016-02-11 12:50:13,424 [main] INFO  CommandLineBagDriver : Returning 2

**Comment by acdha** [comment]
It looks like you're running on a Mac, which explains the `.DS_Store`-related files – do you know what kind of NAS server this is? The logfile above appears to have something to do with getting the resource fork for the Finder's `.DS_Store` files which was certainly a problem on older versions of OS X using NFS but I don't see anything connecting it to video files or file size.

**Comment by hoeyjeinen** [comment]
Hi there!

Thanks very much for the response. I was formerly mounting the NAS using
SMB / CIFS which probably relates to your explanation. However, I find it
strange that it was still allowing me to bag some files/folders and not
others.

Nonetheless, I tried mounting the NAS using AFP and ran the tool again, and
again it worked on some folders but not others. I have a new error message
that is appearing for these failed folders (below). I am not sure how to
interpret this, but is there a hidden file that needs to be deleted, or
perhaps the log files need to be deleted in order for attempt 2 to work?
Let me know what you think. Thanks!

2016-02-16 12:09:37,545 [main] INFO  CommandLineBagDriver : Performing
operation: baginplace
2016-02-16 12:09:37,553 [main] INFO  PreBagImpl : Making a bag in place at
/Volumes/UPM/UPM_0494/Preservation Master
2016-02-16 12:09:37,566 [main] ERROR CommandLineBagDriver : Error:
org.apache.commons.io.FileExistsException: Destination
'/Volumes/UPM/UPM_0494/Preservation Master/data/._UPM_0494_PM.mov' already
exists
java.lang.RuntimeException: org.apache.commons.io.FileExistsException:
Destination '/Volumes/UPM/UPM_0494/Preservation
Master/data/._UPM_0494_PM.mov' already exists
at
gov.loc.repository.bagit.impl.PreBagImpl.makeBagInPlace(PreBagImpl.java:100)
at
gov.loc.repository.bagit.driver.CommandLineBagDriver.performOperation(CommandLineBagDriver.java:852)
at
gov.loc.repository.bagit.driver.CommandLineBagDriver.execute(CommandLineBagDriver.java:411)
at
gov.loc.repository.bagit.driver.CommandLineBagDriver.main(CommandLineBagDriver.java:153)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.codehaus.classworlds.Launcher.launchStandard(Launcher.java:353)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:264)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.commons.io.FileExistsException: Destination
'/Volumes/UPM/UPM_0494/Preservation Master/data/._UPM_0494_PM.mov' already
exists
at org.apache.commons.io.FileUtils.moveFile(FileUtils.java:2099)
at org.apache.commons.io.FileUtils.moveFileToDirectory(FileUtils.java:2144)
at org.apache.commons.io.FileUtils.moveToDirectory(FileUtils.java:2174)
at
gov.loc.repository.bagit.impl.PreBagImpl.makeBagInPlace(PreBagImpl.java:81)
... 11 more
2016-02-16 12:09:37,567 [main] INFO  CommandLineBagDriver : Returning 2

-Joey

**Comment by acdha** [comment]
If yo look at this on a non-Mac, do you see an actual file named `._UPM_0494_PM.mov`? This is one of the problems commonly encountered when switching protocols between AFP, which supports the Mac resource fork, and one which does not, causing the system to write actual `._` files rather than store them in the alternate fork.

**Comment by hoeyjeinen** [comment]
Hi-

Do you mean that a new file is created in the directory called
"_UPM_0494_PM.mov? Things look pretty much the same when I view the file on
a windows machine. Let me know if you meant something else.

-Joey

**Comment by johnscancella** [comment]
To rule out it being something specific to java, could you try using the python version?
https://github.com/LibraryOfCongress/bagit-python

**Comment by hoeyjeinen** [comment]
Hi there-

Thanks for reviving this discussion. I just tried it using Python (version
2.7). I got the following error:

2016-02-26 14:28:42,157 - INFO - creating bag for directory
/Volumes/UPM/UPM_0603/Edit Master

2016-02-26 14:28:42,180 - INFO - creating data dir

2016-02-26 14:28:42,210 - INFO - moving UPM_0603_EM.mov to
/Volumes/UPM/UPM_0603/Edit Master/tmpnVw2W1/UPM_0603_EM.mov

2016-02-26 14:28:42,261 - INFO - moving ._UPM_0603_EM.mov to
/Volumes/UPM/UPM_0603/Edit Master/tmpnVw2W1/._UPM_0603_EM.mov

2016-02-26 14:28:42,261 - ERROR - An error occurred creating the bag

Traceback (most recent call last):

  File "./bagit.py", line 118, in make_bag

    os.rename(f, new_f)

OSError: [Errno 2] No such file or directory

Traceback (most recent call last):

  File "./bagit.py", line 961, in <module>

    logger.info("%s failed to create: %s", bag_dir, e)

NameError: name 'e' is not defined


Perhaps I installed it incorrectly, but it creates a temporary folder and
promptly fails. A new quirk I've learned is that the tool seems to only
work (with the NAS) when its run every few hours (and I know you've already
said that size of file doesn't matter, but the small video files - less
than 1 GB - generally work just fine). When I start for the day the tool
will usually work for the first file (regardless of size) but not any
others subsequently, unless I take a break and come back to it. However,
for any file that received an error it will continuously fail when it's
revisited. I know this is quite anecdotal but I can't figure out why
running the tool is a problem for content on a NAS but has never been a
problem on local machine or an external hard drive. It's a bit
head-spinning.


Let me know if you have any other thoughts.


-Joey

**Comment by johnscancella** [comment]
The fact that it is happening with both libraries rules out anything language specific. What that means is, it is something specific to the NAS, not the tool.
As @acdha mentioned before this is probably due to switching protocols between your mac and the NAS.

**Comment by acdha** [comment]
The underlying problem is that the Mac operating system has the concept of more than one data stream (or fork) for a given filename. This is mostly used for things like metadata such as the Finder's comments, custom icons or labels but, particularly in the past, was sometimes used to store more important data – the classic MacOS text editor would save the text in the main fork and the formatting in the resource fork so you could have rich formatting in a `.txt` file and still be able to give a copy to a DOS or Unix user.

The native Mac filesystems all support this but some network filesystems (e.g. NFS) do not and others (SMB) may or may not depending on the server's filesystem (e.g. [Windows’ NTFS does](https://blogs.technet.microsoft.com/askcore/2013/03/24/alternate-data-streams-in-ntfs/), many others do not) and the particular software implementing SMB and its configuration.

When available, OS X will attempt to use the alternate stream support for the contents of resource forks; when it's not available, it will create the `._` AppleDouble files to store the extra data:

https://support.apple.com/en-us/HT202021

Those `._` files are offered through the filesystem API so Unix applications can back them up or otherwise avoid losing them. It looks like that's the source of the problem which you're seeing. 

It's possible that the patch in #31 could avoid this problem by skipping the `.` files entirely, which would be reasonable for everyone who doesn't need to archive a system which includes real resource fork data (in that case, I'd probably recommend creating a read-only DMG). Otherwise you might need to copy the files to your local system for processing if your local IT department can't help with the NAS configuration.

**Comment by ahva-ubc** [comment]
It's 2021 and I had the same issue as mentioned above. Did patch #31 resolve this? To be more clear, I created my bags using a mac via python3. When I try to validate my bags in windows I get the same error described above. The only thing my log contains is: "2021-09-27 09:57:10,857 [main] INFO  CommandLineBagDriver : Returning 2"

**Comment by jscancella** [comment]
@ahva-ubc try using https://github.com/jscancella/bagging instead

**Comment by ahva-ubc** [comment]
@jscancella Thx! will do.
