### ISSUE TITLE
Error using bagit-4.12.0

### ISSUE THREAD

**Issue by ntallman** [LibraryOfCongress/bagit-java#47]
I just downloaded the release for bagit-4.12.0.zip for use of the command line tools on a RHEL 6 box. When I run a specific bagit command or just ./bagit from the 'bin' directory, I get this error:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: gov/loc/repository/bagit/driver/CommandLineBagDriver : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: gov.loc.repository.bagit.driver.CommandLineBagDriver.  Program will exit.
```
I know that there are plans to remove the CLI in new versions (btw, I think this is a bad idea--many people and programs rely on the CLI) but I thought I would be save using an old 4.x release.

The last line in the 'bagit' file is below. I'm guessing I don't have this class on my local machine?
```
exec "$JAVACMD" "${JVM_OPTS[@]}" -classpath "$CLASSPATH" gov.loc.repository.bagit.driver.CommandLineBagDriver "$@"
```
Any suggestions for solving? I need to make bags from the command line, using the multi-part bag splitting feature of the CLI. Thanks,

**Comment by johnscancella** [comment]
What version of java are you using? the `java.lang.UnsupportedClassVersionError` comes from using an old version of java. version 4.12.0 requires java 1.7 or higher.

Also, have you tried using the python version? If it is missing a feature you could request that it be added.

**Comment by ntallman** [comment]
Sorry, I switched development environments and assumed I had java on the new box. After installing java 1.7, the command is working. 

I fell back to bagit-python when I couldn't get bagit-java to work. I don't think that bagit-python supports the splitbagbysize option. If I'm correct, I think it would be great to add it.

**Comment by johnscancella** [comment]
No problem. I created a task to add the split bag by size in the python version.
