### ISSUE TITLE
some tests fail under windows

### ISSUE THREAD

**Issue by johnscancella** [LibraryOfCongress/bagit-java#52]
from Sheila.Morrissey@ithaka.org
We are looking at adapting your terrific Java Bagit library for use at Portico.

 

One thing I’ve noticed, and am wondering if something is woolly in my configuration, or if others have this problem.

 

I’m running the unit tests in Eclipse (Mars), Java 1.8, on windows 7 - -and bunch of the unit tests are failing - - pretty much on tripping up on filepath strings – or more particularly, the separator – but also simply throwing “file not found” exceptions – reasonably enough, for files/directories that aren’t actually in the resources folders on github - -but I would think Java JVM would also throw exceptions on other OS’s as well.

 

Some details below --  but what I was wondering is if you heard this from anyone else? 

Thanks – and thanks for the terrific work on the Bagit code.

Sheila

 

 

*******************************  some details

 

AddPayloadToBagManifestVistorTest.includeDotKeepFilesInManifest()

 

Path start = Paths.get(getClass().getClassLoader().getResource("dotKeepExampleBag").getFile()).resolve("data");

java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/smorrissey/workspace-nextgen/bagit/target/test-classes/dotKeepExampleBag

  Path start = Paths.get(getClass().getClassLoader().getResource("dotKeepExampleBag").getFile()).resolve("data");

  URL:  file:/C:/Users/smorrissey/workspace-nextgen/bagit/target/test-classes/dotKeepExampleBag

  ULR.getFile  /C:/Users/smorrissey/workspace-nextgen/bagit/target/test-classes/dotKeepExampleBag

 

  so you are doing paths.get() on /C:/Users/smorrissey/workspace-nextgen/bagit/target/test-classes/dotKeepExampleBag

  What you want is paths.get () on C:/Users/smorrissey/workspace-nextgen/bagit/target/test-classes/dotKeepExampleBag

 

  Path start;

                   String osName = System.getProperty("os.name");

                   if (osName.contains("Windows")){

                                  URL url =  getClass().getClassLoader().getResource("dotKeepExampleBag");

                                  String urlFile = url.getFile();

                                  Path basePath = Paths.get(urlFile.substring(1));

                                  start = basePath.resolve("data");

                   }

                   else {

                              start = Paths.get(getClass().getClassLoader().getResource("dotKeepExampleBag").getFile()).resolve("data");

                  }

 

 

AddPayloadToBagManifestVistorTest.testSkipHiddenFile()

   failing at   if(!includeHiddenFiles && Files.isHidden(path) && !path.endsWith(".keep")){ --

  Files.isHidden(path) is throwing an exception because the so-called hidden directory does not in fact exist in resources

 

  

java.nio.file.NoSuchFileException: \foo\.someHiddenDir

               at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)

               at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)

               at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)

               at sun.nio.fs.WindowsFileSystemProvider.isHidden(Unknown Source)

               at java.nio.file.Files.isHidden(Unknown Source)

               at gov.loc.repository.bagit.creator.AddPayloadToBagManifestVistor.visitFile(AddPayloadToBagManifestVistor.java:53)

               at gov.loc.repository.bagit.creator.AddPayloadToBagManifestVistorTest.testSkipHiddenFile(AddPayloadToBagManifestVistorTest.java:57)

               at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

               at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

               at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

               at java.lang.reflect.Method.invoke(Unknown Source)

               at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)

               at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

               at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)

               at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

               at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)

               at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)

               at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)

               at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

               at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

               at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

               at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

               at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

               at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

               at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)

               at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)

               at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)

               at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)

               at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)

               at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

              

Same problem with AddPayloadToBagManifestVistorTest.testSkipHiddenDirectory()

 

Sheila M. Morrissey

Senior Researcher

ITHAKA

100 Campus Drive

Suite 100

Princeton NJ 08540

609-986-2221   

sheila.morrissey@ithaka.org

 

ITHAKA (www.ithaka.org) is a not-for-profit organization that helps the academic community use digital technologies to preserve the scholarly record and to advance research and teaching in sustainable ways.  We provide innovative services that benefit higher education, including Ithaka S+R, JSTOR, and Portico.

**Comment by johnscancella** [comment]
Sheila, with https://github.com/LibraryOfCongress/bagit-java/commit/3822e1de318c75f4d1ead4e89af7e2e8387f1aea this should be fixed.

**Comment by smmorrissey** [comment]
John,
This solved that particular test, but there are about 30 unit test methods that fail because of similar issues.
I have forked and created fixes for these; I'll open a new issue, attach the complete list, and then create a pull request for a fix.
Sheila
